"""create_group_table

Revision ID: 0d7476e7f3c5
Revises: 10716a71f00e
Create Date: 2020-07-23 18:24:40.072383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d7476e7f3c5'
down_revision = '10716a71f00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('createtime', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.Column('is_enable', sa.Boolean(), nullable=True, comment='是否可用'),
    sa.Column('groupname', sa.String(length=30), nullable=False, comment='组名'),
    sa.Column('source_', sa.Text(), nullable=False, comment='资源'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupname')
    )
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.alter_column('user', 'password_code',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False,
               existing_comment='密码')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_comment='用户名')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_comment='用户名')
    op.alter_column('user', 'password_code',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True,
               existing_comment='密码')
    op.drop_table('user_group')
    op.drop_table('group')
    # ### end Alembic commands ###
