"""update_task

Revision ID: 0eefe0e4de5f
Revises: 9737f507013c
Create Date: 2021-03-07 10:14:54.863180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eefe0e4de5f'
down_revision = '9737f507013c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('params_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'params', ['params_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'params_id')
    # ### end Alembic commands ###
