"""update_task_table

Revision ID: 29d87559bc0c
Revises: 681938fc2ac1
Create Date: 2021-03-06 17:21:46.745933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29d87559bc0c'
down_revision = '681938fc2ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task_template', ['template_id'], ['id'])
    op.drop_column('task', 'description')
    op.drop_column('task', 'task_code')
    op.drop_column('task', 'parameter_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('parameter_str', mysql.TEXT(), nullable=False, comment='执行参数'))
    op.add_column('task', sa.Column('task_code', mysql.VARCHAR(length=80), nullable=False, comment='执行脚本'))
    op.add_column('task', sa.Column('description', mysql.VARCHAR(length=1024), nullable=False, comment='任务描述'))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'template_id')
    # ### end Alembic commands ###
