"""delete is_enable

Revision ID: 4d3d178490b7
Revises: 0d7476e7f3c5
Create Date: 2020-09-23 11:07:05.478677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d3d178490b7'
down_revision = '0d7476e7f3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_enable')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'is_enable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否可用'))
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('group', sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否可用'))
    # ### end Alembic commands ###
