"""update_template_table

Revision ID: 5dda03b65708
Revises: a2d58a73df7e
Create Date: 2020-11-30 17:12:29.692992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dda03b65708'
down_revision = 'a2d58a73df7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_action', 'parameter_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_action', sa.Column('parameter_str', mysql.VARCHAR(length=1024), nullable=False, comment='模板动作参数'))
    # ### end Alembic commands ###
