"""create_user_table

Revision ID: 85296da6dfa6
Revises: 4d3d178490b7
Create Date: 2020-11-30 10:13:38.952937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85296da6dfa6'
down_revision = '4d3d178490b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=81), nullable=False, comment='动作名称'),
    sa.Column('action_code', sa.String(length=81), nullable=False, comment='动作脚本'),
    sa.Column('parameter_str', sa.String(length=1024), nullable=False, comment='动作参数'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='任务id'),
    sa.Column('description', sa.String(length=1024), nullable=False, comment='任务描述'),
    sa.Column('parameter_str', sa.Text(), nullable=False, comment='执行参数'),
    sa.Column('task_code', sa.String(length=80), nullable=False, comment='执行脚本'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='任务状态'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_action',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=81), nullable=False, comment='动作名称'),
    sa.Column('action_code', sa.String(length=81), nullable=False, comment='动作脚本'),
    sa.Column('parameter_str', sa.String(length=1024), nullable=False, comment='动作参数'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_action_task_id'), 'task_action', ['task_id'], unique=False)
    op.create_table('task_log',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=27), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['task_action.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_log_task_id'), 'task_log', ['task_id'], unique=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_task_log_task_id'), table_name='task_log')
    op.drop_table('task_log')
    op.drop_index(op.f('ix_task_action_task_id'), table_name='task_action')
    op.drop_table('task_action')
    op.drop_table('task')
    op.drop_table('action')
    # ### end Alembic commands ###
