"""task_log

Revision ID: 88cbecaf8fb0
Revises: dad51064c60a
Create Date: 2021-03-11 21:30:04.476674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cbecaf8fb0'
down_revision = 'dad51064c60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
