"""add_params

Revision ID: 9737f507013c
Revises: 29d87559bc0c
Create Date: 2021-03-06 20:07:49.325254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9737f507013c'
down_revision = '29d87559bc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False, comment='配置id'),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('params_str', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('params')
    # ### end Alembic commands ###
