"""create_template_table

Revision ID: a2d58a73df7e
Revises: 85296da6dfa6
Create Date: 2020-11-30 17:10:10.222145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d58a73df7e'
down_revision = '85296da6dfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_template',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=27), nullable=False, comment='任务模板名称'),
    sa.Column('description', sa.String(length=1024), nullable=False, comment='模板描述'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_action',
    sa.Column('createtime', sa.DateTime(timezone=True), nullable=True, comment='创建时间'),
    sa.Column('updatetime', sa.DateTime(timezone=True), nullable=True, comment='修改时间'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_str', sa.String(length=1024), nullable=False, comment='模板动作参数'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='执行顺序'),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['task_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_action_template_id'), 'template_action', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_action_template_id'), table_name='template_action')
    op.drop_table('template_action')
    op.drop_table('task_template')
    # ### end Alembic commands ###
